---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: metrics
spec:
  interval: 5m0s
  path: ./flux/apps/aks-sa-lab-001/kube-state-metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

