---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-state-metrics
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: '>4.30.0'
  interval: 10m0s

